object(character).
characters(character).
object(bedroom).
rooms(bedroom).
object(floor).
surfaces(floor).
floors(floor).
object(wall).
walls(wall).
object(window).
windows(window).
object(ceiling).
ceiling(ceiling).
object(ceilinglamp).
lamps(ceilinglamp).
object(tablelamp).
on(tablelamp).
has_switch(tablelamp).
has_plug(tablelamp).
lamps(tablelamp).
object(garbagecan).
containers(garbagecan).
movable(garbagecan).
furniture(garbagecan).
object(nightstand).
surfaces(nightstand).
containers(nightstand).
furniture(nightstand).
object(bookshelf).
surfaces(bookshelf).
containers(bookshelf).
furniture(bookshelf).
object(chair).
surfaces(chair).
grabbable(chair).
sittable(chair).
movable(chair).
furniture(chair).
object(desk).
surfaces(desk).
movable(desk).
furniture(desk).
object(bed).
surfaces(bed).
sittable(bed).
lieable(bed).
furniture(bed).
object(coffeetable).
surfaces(coffeetable).
movable(coffeetable).
furniture(coffeetable).
object(closet).
containers(closet).
furniture(closet).
object(hanger).
grabbable(hanger).
hangable(hanger).
movable(hanger).
furniture(hanger).
object(closetdrawer).
furniture(closetdrawer).
object(clothesshirt).
grabbable(clothesshirt).
hangable(clothesshirt).
clothes(clothesshirt).
movable(clothesshirt).
furniture(clothesshirt).
object(clothespants).
grabbable(clothespants).
hangable(clothespants).
clothes(clothespants).
movable(clothespants).
furniture(clothespants).
object(clothespile).
grabbable(clothespile).
containers(clothespile).
movable(clothespile).
furniture(clothespile).
object(doorjamb).
doors(doorjamb).
object(mouse).
grabbable(mouse).
has_plug(mouse).
movable(mouse).
electronics(mouse).
object(mousemat).
surfaces(mousemat).
movable(mousemat).
electronics(mousemat).
object(keyboard).
grabbable(keyboard).
has_plug(keyboard).
movable(keyboard).
electronics(keyboard).
object(lightswitch).
on(lightswitch).
has_switch(lightswitch).
has_plug(lightswitch).
electronics(lightswitch).
object(computer).
off(computer).
has_switch(computer).
lookable(computer).
electronics(computer).
object(cpuscreen).
electronics(cpuscreen).
object(radio).
off(radio).
surfaces(radio).
grabbable(radio).
has_switch(radio).
has_plug(radio).
movable(radio).
electronics(radio).
object(rug).
surfaces(rug).
grabbable(rug).
sittable(rug).
lieable(rug).
movable(rug).
decor(rug).
object(wallpictureframe).
grabbable(wallpictureframe).
hangable(wallpictureframe).
has_paper(wallpictureframe).
movable(wallpictureframe).
decor(wallpictureframe).
object(candle).
off(candle).
grabbable(candle).
has_switch(candle).
movable(candle).
decor(candle).
object(orchid).
decor(orchid).
object(curtains).
cover_object(curtains).
movable(curtains).
decor(curtains).
object(pillow).
grabbable(pillow).
movable(pillow).
decor(pillow).
object(cellphone).
off(cellphone).
grabbable(cellphone).
has_switch(cellphone).
has_plug(cellphone).
movable(cellphone).
props(cellphone).
object(photoframe).
props(photoframe).
object(book).
grabbable(book).
cuttable(book).
readable(book).
has_paper(book).
movable(book).
props(book).
object(box).
grabbable(box).
recipient(box).
containers(box).
cover_object(box).
movable(box).
props(box).
object(plate).
surfaces(plate).
grabbable(plate).
recipient(plate).
movable(plate).
props(plate).
object(mug).
grabbable(mug).
recipient(mug).
pourable(mug).
movable(mug).
props(mug).
object(cupcake).
grabbable(cupcake).
eatable(cupcake).
movable(cupcake).
props(cupcake).
object(wineglass).
grabbable(wineglass).
recipient(wineglass).
pourable(wineglass).
movable(wineglass).
props(wineglass).
object(slippers).
grabbable(slippers).
hangable(slippers).
clothes(slippers).
movable(slippers).
props(slippers).
object(folder).
grabbable(folder).
readable(folder).
containers(folder).
has_paper(folder).
movable(folder).
props(folder).
object(livingroom).
rooms(livingroom).
object(walllamp).
lamps(walllamp).
object(sofa).
surfaces(sofa).
sittable(sofa).
lieable(sofa).
movable(sofa).
furniture(sofa).
object(tvstand).
surfaces(tvstand).
movable(tvstand).
furniture(tvstand).
object(cabinet).
surfaces(cabinet).
containers(cabinet).
furniture(cabinet).
object(tv).
off(tv).
has_switch(tv).
lookable(tv).
has_plug(tv).
electronics(tv).
object(powersocket).
electronics(powersocket).
object(apple).
grabbable(apple).
movable(apple).
props(apple).
object(bananas).
grabbable(bananas).
movable(bananas).
props(bananas).
object(lime).
grabbable(lime).
movable(lime).
props(lime).
object(peach).
props(peach).
object(plum).
grabbable(plum).
movable(plum).
props(plum).
object(dishbowl).
grabbable(dishbowl).
recipient(dishbowl).
movable(dishbowl).
props(dishbowl).
object(paper).
grabbable(paper).
readable(paper).
has_paper(paper).
movable(paper).
props(paper).
object(remotecontrol).
off(remotecontrol).
grabbable(remotecontrol).
has_switch(remotecontrol).
movable(remotecontrol).
props(remotecontrol).
object(crackers).
grabbable(crackers).
movable(crackers).
food(crackers).
object(washingsponge).
grabbable(washingsponge).
movable(washingsponge).
props(washingsponge).
object(salmon).
grabbable(salmon).
movable(salmon).
food(salmon).
object(coffeemaker).
off(coffeemaker).
recipient(coffeemaker).
has_switch(coffeemaker).
containers(coffeemaker).
has_plug(coffeemaker).
movable(coffeemaker).
appliances(coffeemaker).
object(kitchen).
rooms(kitchen).
object(cereal).
grabbable(cereal).
eatable(cereal).
movable(cereal).
food(cereal).
object(bathtub).
sittable(bathtub).
lieable(bathtub).
furniture(bathtub).
object(toothpaste).
grabbable(toothpaste).
pourable(toothpaste).
movable(toothpaste).
cream(toothpaste).
props(toothpaste).
object(faucet).
off(faucet).
has_switch(faucet).
furniture(faucet).
object(creamybuns).
grabbable(creamybuns).
eatable(creamybuns).
cuttable(creamybuns).
movable(creamybuns).
food(creamybuns).
object(kitchencabinet).
surfaces(kitchencabinet).
containers(kitchencabinet).
furniture(kitchencabinet).
object(microwave).
off(microwave).
has_switch(microwave).
containers(microwave).
has_plug(microwave).
appliances(microwave).
object(breadslice).
grabbable(breadslice).
eatable(breadslice).
cuttable(breadslice).
movable(breadslice).
appliances(breadslice).
object(facecream).
grabbable(facecream).
pourable(facecream).
movable(facecream).
cream(facecream).
props(facecream).
object(kitchentable).
surfaces(kitchentable).
movable(kitchentable).
furniture(kitchentable).
object(bellpepper).
grabbable(bellpepper).
movable(bellpepper).
food(bellpepper).
object(barsoap).
grabbable(barsoap).
movable(barsoap).
cream(barsoap).
props(barsoap).
object(oventray).
surfaces(oventray).
grabbable(oventray).
movable(oventray).
appliances(oventray).
object(towelrack).
surfaces(towelrack).
grabbable(towelrack).
movable(towelrack).
furniture(towelrack).
object(fryingpan).
surfaces(fryingpan).
grabbable(fryingpan).
recipient(fryingpan).
containers(fryingpan).
movable(fryingpan).
props(fryingpan).
object(bathroomcabinet).
surfaces(bathroomcabinet).
containers(bathroomcabinet).
furniture(bathroomcabinet).
object(dishwashingliquid).
grabbable(dishwashingliquid).
pourable(dishwashingliquid).
movable(dishwashingliquid).
cream(dishwashingliquid).
props(dishwashingliquid).
object(condimentbottle).
grabbable(condimentbottle).
pourable(condimentbottle).
movable(condimentbottle).
cream(condimentbottle).
props(condimentbottle).
object(pie).
grabbable(pie).
eatable(pie).
cuttable(pie).
movable(pie).
food(pie).
object(painkillers).
props(painkillers).
object(kitchencounterdrawer).
furniture(kitchencounterdrawer).
object(wallphone).
off(wallphone).
grabbable(wallphone).
has_switch(wallphone).
has_plug(wallphone).
movable(wallphone).
electronics(wallphone).
object(coffeepot).
grabbable(coffeepot).
recipient(coffeepot).
movable(coffeepot).
appliances(coffeepot).
object(deodorant).
props(deodorant).
object(hairproduct).
grabbable(hairproduct).
pourable(hairproduct).
movable(hairproduct).
props(hairproduct).
object(door).
doors(door).
object(toilet).
sittable(toilet).
containers(toilet).
furniture(toilet).
object(candybar).
grabbable(candybar).
eatable(candybar).
movable(candybar).
food(candybar).
object(stall).
furniture(stall).
object(cutleryfork).
grabbable(cutleryfork).
movable(cutleryfork).
props(cutleryfork).
object(kitchencounter).
surfaces(kitchencounter).
furniture(kitchencounter).
object(whippedcream).
grabbable(whippedcream).
eatable(whippedcream).
cuttable(whippedcream).
movable(whippedcream).
food(whippedcream).
object(stovefan).
appliances(stovefan).
object(bathroom).
rooms(bathroom).
object(chocolatesyrup).
grabbable(chocolatesyrup).
eatable(chocolatesyrup).
cuttable(chocolatesyrup).
movable(chocolatesyrup).
food(chocolatesyrup).
object(cutleryknife).
grabbable(cutleryknife).
movable(cutleryknife).
props(cutleryknife).
object(clock).
off(clock).
grabbable(clock).
has_switch(clock).
lookable(clock).
has_plug(clock).
movable(clock).
electronics(clock).
object(toaster).
off(toaster).
has_switch(toaster).
containers(toaster).
has_plug(toaster).
movable(toaster).
appliances(toaster).
object(toothbrush).
grabbable(toothbrush).
recipient(toothbrush).
movable(toothbrush).
props(toothbrush).
object(wallshelf).
furniture(wallshelf).
object(perfume).
props(perfume).
object(towel).
grabbable(towel).
cover_object(towel).
movable(towel).
props(towel).
object(bathroomcounter).
surfaces(bathroomcounter).
furniture(bathroomcounter).
object(waterglass).
grabbable(waterglass).
recipient(waterglass).
pourable(waterglass).
movable(waterglass).
props(waterglass).
object(fridge).
has_switch(fridge).
containers(fridge).
has_plug(fridge).
appliances(fridge).
object(condimentshaker).
grabbable(condimentshaker).
eatable(condimentshaker).
pourable(condimentshaker).
movable(condimentshaker).
props(condimentshaker).
object(chips).
grabbable(chips).
movable(chips).
food(chips).
object(sink).
recipient(sink).
containers(sink).
furniture(sink).
object(washingmachine).
off(washingmachine).
recipient(washingmachine).
has_switch(washingmachine).
containers(washingmachine).
has_plug(washingmachine).
appliances(washingmachine).
object(bench).
surfaces(bench).
sittable(bench).
lieable(bench).
movable(bench).
furniture(bench).
object(stove).
off(stove).
surfaces(stove).
has_switch(stove).
containers(stove).
appliances(stove).
